Document: udp-filters
Title: Debian udp-filters Manual
Author: <insert document author here>
Abstract: This manual describes what udp-filters is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/udp-filters/udp-filters.sgml.gz

Format: postscript
Files: /usr/share/doc/udp-filters/udp-filters.ps.gz

Format: text
Files: /usr/share/doc/udp-filters/udp-filters.text.gz

Format: HTML
Index: /usr/share/doc/udp-filters/html/index.html
Files: /usr/share/doc/udp-filters/html/*.html
